# Use the latest 2.1 version of CircleCI pipeline process engine.
# See: https://circleci.com/docs/2.0/configuration-reference
version: 2.1

# Define a job to be invoked later in a workflow.
# See: https://circleci.com/docs/2.0/configuration-reference/#jobs
jobs:
  print_hello:
    docker:
      - image: circleci/node:13.8.0
    steps:
      - checkout
      - run:
          name: "print Hello"
          command: "echo Hello!"
  print_world:
    docker:
      - image: circleci/node:13.8.0
    steps:
      - checkout
      - run:
          name: "print Hello World"
          command: "echo  Hello, World!"
  print_Name:
    docker:
      - image: circleci/node:13.8.0
    steps:
      - checkout
      - run:
          name: "print my name"
          command: "echo  My name is ${NAME}"

workflows:
  First-workflow:
    jobs:
      - print_hello
      - print_world:
          requires:
            - print_hello
      -  print_Name


